development:
  clients:
    default:
      database: tests_app_api_development

      hosts:
        - 82.148.16.231:27017
      options:
        raise_not_found_error: false

  options:
    raise_not_found_error: false

test:
  clients:
    default:
      database: tests_app_api_test
      hosts:
        - localhost:27017
      options:
        raise_not_found_error: false
        read:
          mode: :primary
        max_pool_size: 1
